"""Output builder for constructing hook output JSON.

This module provides a unified output construction mechanism that merges
accumulator results with hardcoded context from built-in logic.
"""

from collections.abc import Callable
from dataclasses import dataclass
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from oaps.enums import HookEventType

    from ._action import OutputAccumulator


@dataclass(slots=True)
class HardcodedContext:
    """Context generated by built-in hook logic.

    Attributes:
        additional_context: Context string to inject (SessionStart, PreCompact).
    """

    additional_context: str | None = None


def _merge_context(
    hardcoded: str | None,
    accumulator_items: list[str],
) -> str | None:
    """Merge hardcoded context with accumulator items.

    Hardcoded context comes first, then accumulator items joined with newlines.

    Args:
        hardcoded: Optional hardcoded context string.
        accumulator_items: List of context items from rules.

    Returns:
        Merged context string, or None if both are empty.
    """
    parts: list[str] = []
    if hardcoded:
        parts.append(hardcoded)
    parts.extend(accumulator_items)

    if not parts:
        return None
    return "\n".join(parts)


def _merge_system_messages(messages: list[str]) -> str | None:
    """Join system messages with newlines.

    Args:
        messages: List of system messages from rules.

    Returns:
        Joined messages, or None if empty.
    """
    if not messages:
        return None
    return "\n".join(messages)


def _build_session_start_output(
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext,
) -> str | None:
    """Build SessionStart output JSON.

    Args:
        accumulator: The output accumulator from rule execution.
        hardcoded: Hardcoded context from built-in logic.

    Returns:
        JSON string for SessionStart output, or None if no output.
    """
    from ._outputs import (  # noqa: PLC0415
        SessionStartHookSpecificOutput,
        SessionStartOutput,
    )

    additional_context = _merge_context(
        hardcoded.additional_context,
        accumulator.additional_context_items,
    )
    system_message = _merge_system_messages(accumulator.system_messages)

    # Only output if there's something to output
    if additional_context is None and system_message is None:
        return None

    output = SessionStartOutput(
        system_message=system_message,
        hook_specific_output=SessionStartHookSpecificOutput(
            additional_context=additional_context,
        )
        if additional_context
        else None,
    )
    return output.to_output_json()


def _build_pre_tool_use_output(
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext,
) -> str | None:
    """Build PreToolUse output JSON.

    Args:
        accumulator: The output accumulator from rule execution.
        hardcoded: Hardcoded context from built-in logic (unused for PreToolUse).

    Returns:
        JSON string for PreToolUse output, or None if no output.
    """
    del hardcoded  # PreToolUse doesn't use additional context
    from ._outputs import (  # noqa: PLC0415
        PreToolUseHookSpecificOutput,
        PreToolUseOutput,
    )

    system_message = _merge_system_messages(accumulator.system_messages)

    # Only output if there's a permission decision, updated input, or system message
    if (
        accumulator.permission_decision is None
        and accumulator.updated_input is None
        and system_message is None
    ):
        return None

    hook_specific: PreToolUseHookSpecificOutput | None = None
    if (
        accumulator.permission_decision is not None
        or accumulator.updated_input is not None
    ):
        hook_specific = PreToolUseHookSpecificOutput(
            permission_decision=accumulator.permission_decision,
            permission_decision_reason=accumulator.permission_decision_reason,
            updated_input=accumulator.updated_input,
        )

    output = PreToolUseOutput(
        system_message=system_message,
        hook_specific_output=hook_specific,
    )
    return output.to_output_json()


def _build_post_tool_use_output(
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext,
) -> str | None:
    """Build PostToolUse output JSON.

    Args:
        accumulator: The output accumulator from rule execution.
        hardcoded: Hardcoded context from built-in logic.

    Returns:
        JSON string for PostToolUse output, or None if no output.
    """
    from ._outputs import (  # noqa: PLC0415
        PostToolUseHookSpecificOutput,
        PostToolUseOutput,
    )

    additional_context = _merge_context(
        hardcoded.additional_context,
        accumulator.additional_context_items,
    )
    system_message = _merge_system_messages(accumulator.system_messages)

    if additional_context is None and system_message is None:
        return None

    output = PostToolUseOutput(
        system_message=system_message,
        hook_specific_output=PostToolUseHookSpecificOutput(
            additional_context=additional_context,
        )
        if additional_context
        else None,
    )
    return output.to_output_json()


def _build_user_prompt_submit_output(
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext,
) -> str | None:
    """Build UserPromptSubmit output JSON.

    Args:
        accumulator: The output accumulator from rule execution.
        hardcoded: Hardcoded context from built-in logic.

    Returns:
        JSON string for UserPromptSubmit output, or None if no output.
    """
    from ._outputs import (  # noqa: PLC0415
        UserPromptSubmitHookSpecificOutput,
        UserPromptSubmitOutput,
    )

    additional_context = _merge_context(
        hardcoded.additional_context,
        accumulator.additional_context_items,
    )
    system_message = _merge_system_messages(accumulator.system_messages)

    if additional_context is None and system_message is None:
        return None

    output = UserPromptSubmitOutput(
        system_message=system_message,
        hook_specific_output=UserPromptSubmitHookSpecificOutput(
            additional_context=additional_context,
        )
        if additional_context
        else None,
    )
    return output.to_output_json()


def _build_permission_request_output(
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext,
) -> str | None:
    """Build PermissionRequest output JSON.

    Args:
        accumulator: The output accumulator from rule execution.
        hardcoded: Hardcoded context from built-in logic (unused).

    Returns:
        JSON string for PermissionRequest output, or None if no output.
    """
    del hardcoded  # PermissionRequest doesn't use additional context
    from ._outputs import (  # noqa: PLC0415
        PermissionRequestHookSpecificOutput,
        PermissionRequestOutput,
    )

    system_message = _merge_system_messages(accumulator.system_messages)

    # Only output if there's a decision or system message
    if accumulator.permission_request_decision is None and system_message is None:
        return None

    hook_specific: PermissionRequestHookSpecificOutput | None = None
    if accumulator.permission_request_decision is not None:
        hook_specific = PermissionRequestHookSpecificOutput(
            decision=accumulator.permission_request_decision,
        )

    output = PermissionRequestOutput(
        system_message=system_message,
        hook_specific_output=hook_specific,
    )
    return output.to_output_json()


def _build_pre_compact_output(
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext,
) -> str | None:
    """Build PreCompact output JSON.

    Args:
        accumulator: The output accumulator from rule execution.
        hardcoded: Hardcoded context from built-in logic (statistics).

    Returns:
        JSON string for PreCompact output, or None if no output.
    """
    from ._outputs import (  # noqa: PLC0415
        PreCompactHookSpecificOutput,
        PreCompactOutput,
    )

    additional_context = _merge_context(
        hardcoded.additional_context,
        accumulator.additional_context_items,
    )
    system_message = _merge_system_messages(accumulator.system_messages)

    if additional_context is None and system_message is None:
        return None

    output = PreCompactOutput(
        system_message=system_message,
        hook_specific_output=PreCompactHookSpecificOutput(
            additional_context=additional_context,
        )
        if additional_context
        else None,
    )
    return output.to_output_json()


def _build_notification_output(
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext,
) -> str | None:
    """Build Notification output JSON.

    Args:
        accumulator: The output accumulator from rule execution.
        hardcoded: Hardcoded context from built-in logic (unused).

    Returns:
        JSON string for Notification output, or None if no output.
    """
    del hardcoded  # Notification doesn't use additional context
    from ._outputs import NotificationOutput  # noqa: PLC0415

    system_message = _merge_system_messages(accumulator.system_messages)

    if system_message is None:
        return None

    output = NotificationOutput(system_message=system_message)
    return output.to_output_json()


def _build_stop_output(
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext,
) -> str | None:
    """Build Stop output JSON.

    Args:
        accumulator: The output accumulator from rule execution.
        hardcoded: Hardcoded context from built-in logic (unused).

    Returns:
        JSON string for Stop output, or None if no output.
    """
    del hardcoded  # Stop doesn't use additional context
    from ._outputs import StopOutput  # noqa: PLC0415

    system_message = _merge_system_messages(accumulator.system_messages)

    if system_message is None:
        return None

    output = StopOutput(system_message=system_message)
    return output.to_output_json()


def _build_subagent_stop_output(
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext,
) -> str | None:
    """Build SubagentStop output JSON.

    Args:
        accumulator: The output accumulator from rule execution.
        hardcoded: Hardcoded context from built-in logic (unused).

    Returns:
        JSON string for SubagentStop output, or None if no output.
    """
    del hardcoded  # SubagentStop doesn't use additional context
    from ._outputs import SubagentStopOutput  # noqa: PLC0415

    system_message = _merge_system_messages(accumulator.system_messages)

    if system_message is None:
        return None

    output = SubagentStopOutput(system_message=system_message)
    return output.to_output_json()


def _build_session_end_output(
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext,
) -> str | None:
    """Build SessionEnd output JSON.

    SessionEnd produces no meaningful output.

    Args:
        accumulator: The output accumulator from rule execution (unused).
        hardcoded: Hardcoded context from built-in logic (unused).

    Returns:
        Always None for SessionEnd.
    """
    del accumulator, hardcoded  # SessionEnd doesn't produce output
    return None


# Type alias for output builder functions
OutputBuilderFn = Callable[["OutputAccumulator", HardcodedContext], str | None]


def build_hook_output(
    event: HookEventType,
    accumulator: OutputAccumulator,
    hardcoded: HardcodedContext | None = None,
) -> str | None:
    """Build hook output JSON for the given event type.

    Dispatches to event-specific output builders that merge accumulator
    results with hardcoded context.

    Args:
        event: The hook event type.
        accumulator: The output accumulator from rule execution.
        hardcoded: Optional hardcoded context from built-in logic.

    Returns:
        JSON string for hook output, or None if no output needed.
    """
    from oaps.enums import HookEventType  # noqa: PLC0415

    if hardcoded is None:
        hardcoded = HardcodedContext()

    # Dispatch table mapping event types to builders
    builders: dict[HookEventType, OutputBuilderFn] = {
        HookEventType.SESSION_START: _build_session_start_output,
        HookEventType.PRE_TOOL_USE: _build_pre_tool_use_output,
        HookEventType.POST_TOOL_USE: _build_post_tool_use_output,
        HookEventType.USER_PROMPT_SUBMIT: _build_user_prompt_submit_output,
        HookEventType.PERMISSION_REQUEST: _build_permission_request_output,
        HookEventType.PRE_COMPACTION: _build_pre_compact_output,
        HookEventType.NOTIFICATION: _build_notification_output,
        HookEventType.STOP: _build_stop_output,
        HookEventType.SUBAGENT_STOP: _build_subagent_stop_output,
        HookEventType.SESSION_END: _build_session_end_output,
    }

    builder = builders.get(event)
    if builder is None:
        return None

    return builder(accumulator, hardcoded)
