"""Utility functions for OAPS."""

from ._author import AuthorInfo, get_author_info
from ._claude_plugin import get_claude_plugin_dir, get_claude_plugin_skills_dir
from ._detect import detect_tooling
from ._exec import (
    PythonConfig,
    PythonResult,
    ScriptConfig,
    ScriptResult,
    parse_entrypoint,
    run_python,
    run_script,
    truncate_output,
)
from ._git import (
    GitContext,
    WorktreeAddResult,
    WorktreeInfo,
    WorktreePruneResult,
    add_worktree,
    get_git_context,
    get_main_worktree,
    get_worktree,
    get_worktree_for_path,
    is_in_worktree,
    is_main_worktree,
    list_worktrees,
    lock_worktree,
    move_worktree,
    prune_worktrees,
    remove_worktree,
    unlock_worktree,
)
from ._ignore import (
    DEFAULT_IGNORE_PATTERNS,
    IgnoreConfig,
    collect_patterns,
    create_pathspec,
    load_gitignore_patterns,
)
from ._logging import create_cli_logger, create_hooks_logger, create_session_logger
from ._paths import (
    get_claude_config_dir,
    get_oaps_cli_log_file,
    get_oaps_dir,
    get_oaps_hooks_log_file,
    get_oaps_log_dir,
    get_oaps_overrides_dir,
    get_oaps_session_log_file,
    get_oaps_skill_overrides_dir,
    get_oaps_state_db,
    get_oaps_state_file,
    get_package_dir,
    get_plans_dir,
    get_project_skill_dir,
    get_project_skills_dir,
    get_worktree_root,
)
from ._project import is_oaps_project
from ._state_store import (
    MockStateStore,
    SQLiteStateStore,
    StateEntry,
    StateStore,
    StateStoreKey,
    StateStoreValue,
    create_project_store,
    create_session_store,
    create_state_store,
)

__all__ = [
    "DEFAULT_IGNORE_PATTERNS",
    "AuthorInfo",
    "GitContext",
    "IgnoreConfig",
    "MockStateStore",
    "PythonConfig",
    "PythonResult",
    "SQLiteStateStore",
    "ScriptConfig",
    "ScriptResult",
    "StateEntry",
    "StateStore",
    "StateStoreKey",
    "StateStoreValue",
    "WorktreeAddResult",
    "WorktreeInfo",
    "WorktreePruneResult",
    "add_worktree",
    "collect_patterns",
    "create_cli_logger",
    "create_hooks_logger",
    "create_pathspec",
    "create_project_store",
    "create_session_logger",
    "create_session_store",
    "create_state_store",
    "detect_tooling",
    "get_author_info",
    "get_claude_config_dir",
    "get_claude_plugin_dir",
    "get_claude_plugin_skills_dir",
    "get_git_context",
    "get_main_worktree",
    "get_oaps_cli_log_file",
    "get_oaps_dir",
    "get_oaps_hooks_log_file",
    "get_oaps_log_dir",
    "get_oaps_overrides_dir",
    "get_oaps_session_log_file",
    "get_oaps_skill_overrides_dir",
    "get_oaps_state_db",
    "get_oaps_state_file",
    "get_package_dir",
    "get_plans_dir",
    "get_project_skill_dir",
    "get_project_skills_dir",
    "get_worktree",
    "get_worktree_for_path",
    "get_worktree_root",
    "is_in_worktree",
    "is_main_worktree",
    "is_oaps_project",
    "list_worktrees",
    "load_gitignore_patterns",
    "lock_worktree",
    "move_worktree",
    "parse_entrypoint",
    "prune_worktrees",
    "remove_worktree",
    "run_python",
    "run_script",
    "truncate_output",
    "unlock_worktree",
]
