"""OAPS specification system data models.

This package provides all enums and dataclasses for the specification system,
including specifications, requirements, tests, artifacts, and their supporting
structures.
"""

from oaps.spec._artifact_manager import ArtifactManager
from oaps.spec._history_manager import HistoryManager
from oaps.spec._ids import (
    CrossReference,
    ParsedID,
    ValidationResult,
    next_artifact_id,
    next_requirement_id,
    next_spec_id,
    next_sub_requirement_id,
    next_test_id,
    parse_cross_reference,
    validate_artifact_id,
    validate_cross_reference,
    validate_requirement_id,
    validate_spec_id,
    validate_test_id,
)
from oaps.spec._io import (
    append_jsonl,
    read_json,
    read_jsonl,
    read_markdown_frontmatter,
    write_json_atomic,
    write_markdown_with_frontmatter,
)
from oaps.spec._models import (
    Artifact,
    ArtifactsContainer,
    ArtifactStatus,
    ArtifactType,
    Counts,
    CoverageReport,
    DependencyGraph,
    DependencyNode,
    Document,
    DocumentType,
    ExternalReference,
    ExternalRefType,
    HistoryEntry,
    MethodCoverage,
    OrphanReport,
    ProgressReport,
    PytestResults,
    PytestTest,
    RebuildResult,
    RelationshipEdge,
    RelationshipGraph,
    Relationships,
    RelationshipType,
    Requirement,
    RequirementsContainer,
    RequirementStatus,
    RequirementType,
    RootIndex,
    SpecMetadata,
    SpecNode,
    SpecStatus,
    SpecSummary,
    SpecType,
    SyncResult,
    Test,
    TestMethod,
    TestResult,
    TestsContainer,
    TestStatus,
    TypeCoverage,
    TypeProgress,
)
from oaps.spec._query_manager import QueryManager
from oaps.spec._requirement_manager import RequirementManager
from oaps.spec._spec_manager import SpecManager, SpecValidationIssue
from oaps.spec._test_manager import TestManager

__all__ = [
    "Artifact",
    "ArtifactManager",
    "ArtifactStatus",
    "ArtifactType",
    "ArtifactsContainer",
    "Counts",
    "CoverageReport",
    "CrossReference",
    "DependencyGraph",
    "DependencyNode",
    "Document",
    "DocumentType",
    "ExternalRefType",
    "ExternalReference",
    "HistoryEntry",
    "HistoryManager",
    "MethodCoverage",
    "OrphanReport",
    "ParsedID",
    "ProgressReport",
    "PytestResults",
    "PytestTest",
    "QueryManager",
    "RebuildResult",
    "RelationshipEdge",
    "RelationshipGraph",
    "RelationshipType",
    "Relationships",
    "Requirement",
    "RequirementManager",
    "RequirementStatus",
    "RequirementType",
    "RequirementsContainer",
    "RootIndex",
    "SpecManager",
    "SpecMetadata",
    "SpecNode",
    "SpecStatus",
    "SpecSummary",
    "SpecType",
    "SpecValidationIssue",
    "SyncResult",
    "Test",
    "TestManager",
    "TestMethod",
    "TestResult",
    "TestStatus",
    "TestsContainer",
    "TypeCoverage",
    "TypeProgress",
    "ValidationResult",
    "append_jsonl",
    "next_artifact_id",
    "next_requirement_id",
    "next_spec_id",
    "next_sub_requirement_id",
    "next_test_id",
    "parse_cross_reference",
    "read_json",
    "read_jsonl",
    "read_markdown_frontmatter",
    "validate_artifact_id",
    "validate_cross_reference",
    "validate_requirement_id",
    "validate_spec_id",
    "validate_test_id",
    "write_json_atomic",
    "write_markdown_with_frontmatter",
]
